version: '3'
services:
  cyb-redis-demo:
    container_name: cyb-redis-demo
    image: hustcyb/cyb-redis-demo:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    volumes:
      - ./java/application.yml:/data/cyb-redis-demo/config/application.yml
    links:
      - redis-master

  redis-slave1:
    container_name: redis-slave1
    image: redis
    expose:
      - "6379"
    volumes:
      - ./redis-slave1/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    links:
      - redis-master

  redis-slave2:
    container_name: redis-slave2
    image: redis
    expose:
      - "6379"
    volumes:
      - ./redis-slave2/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    links:
      - redis-master

  redis-master:
    container_name: redis-master
    image: redis
    expose:
      - "6379"
    volumes:
      - ./redis-master/data:/data
      - ./redis-master/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes