version: '3'
services:
  cyb-redis-demo:
    container_name: cyb-redis-demo
    image: hustcyb/cyb-redis-demo:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    volumes:
      - ./java/application.yml:/data/cyb-redis-demo/config/application.yml
    links:
      - redis-sentinel

  redis-master:
    image: redis-master
    build: ./redis-master
    expose:
      - "6379"

  redis-slave:
    image: redis-slave
    build: ./redis-slave
    expose:
      - "6379"
    links:
      - redis-master

  redis-sentinel:
    image: redis-sentinel
    build: ./redis-sentinel
    expose:
      - "26379"
    links:
      - redis-master